package com.rakshaksetu.app.evidence

import android.os.Build
import com.rakshaksetu.app.model.DetectionResult
import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

/**
 * Statutory Section 65B Electronic Evidence Certificate Generator.
 * Compliant with Section 65B of the Indian Evidence Act, 1872 &
 * Sections 63/65 of the Bharatiya Sakshya Adhiniyam (BSA), 2023.
 *
 * Implements Section 19 (Page 65) of the Master Defense Specification.
 */
object Section65BCertificateGenerator {

    data class StatutoryCertificate(
        val certificateText: String,
        val sha256Checksum: String,
        val timestampIso: String,
        val legalStatute: String = "Bharatiya Sakshya Adhiniyam, 2023 (Section 63/65) & Indian Evidence Act (Section 65B)"
    )

    fun generateCertificate(
        result: DetectionResult,
        complainantName: String = "[Complainant Full Name]",
        complainantAddress: String = "[Complainant Address]",
        deviceImei: String = "EMBEDDED_SECURE_DEVICE_ID",
        extractedUpiIds: List<String> = emptyList(),
        extractedBankAccounts: List<String> = emptyList()
    ): StatutoryCertificate {
        val dateFormat = SimpleDateFormat("dd-MM-yyyy", Locale.US).apply {
            timeZone = TimeZone.getTimeZone("Asia/Kolkata")
        }
        val timeFormat = SimpleDateFormat("HH:mm:ss 'IST'", Locale.US).apply {
            timeZone = TimeZone.getTimeZone("Asia/Kolkata")
        }
        val isoFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)

        val epochMs = if (result.callEndEpoch > 100_000_000_000L) result.callEndEpoch else result.callEndEpoch * 1000L
        val dateStr = dateFormat.format(Date(epochMs))
        val timeStr = timeFormat.format(Date(epochMs))
        val isoTimestamp = isoFormat.format(Date(epochMs))

        val osBuild = "${Build.MANUFACTURER} ${Build.MODEL} (Android ${Build.VERSION.RELEASE}, API ${Build.VERSION.SDK_INT}, Build: ${Build.DISPLAY})"

        val rawDataToHash = "${result.callId}|${result.phoneNumber}|$epochMs|${result.durationSec}|${result.fullTranscript}|${result.confidence}"
        val sha256 = MessageDigest.getInstance("SHA-256")
            .digest(rawDataToHash.toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }

        val upiStr = if (extractedUpiIds.isNotEmpty()) extractedUpiIds.joinToString(", ") else "None detected"
        val acctStr = if (extractedBankAccounts.isNotEmpty()) extractedBankAccounts.joinToString(", ") else "None detected"

        val certificateText = """
====================================================================================================
      CERTIFICATE UNDER SECTION 65B OF THE INDIAN EVIDENCE ACT, 1872 &
          SECTIONS 63/65 OF THE BHARATIYA SAKSHYA ADHINIYAM, 2023
           FOR ADMISSIBILITY OF ELECTRONIC FORENSIC RECORDS IN COURT
====================================================================================================

I, $complainantName, residing at $complainantAddress, do hereby solemnly affirm and state:

1. That I am the registered subscriber and lawful custodian of mobile device identifier: $deviceImei,
   running Operating System Build Fingerprint: $osBuild.

2. That the electronic records contained in the accompanying Forensic Cybercrime Evidence Dossier,
   bearing Unique Investigation SHA-256 Hash [$sha256], were produced by the mobile device during
   its lawful and ordinary operation by the cyber defense application 'Rakshak Setu'.

3. That on $dateStr at $timeStr, an incoming telephonic communication was established
   from Calling Line Identification (CLI): ${result.phoneNumber}.

4. That throughout the material period, the computer system and acoustic processing algorithms of
   Rakshak Setu were operating properly and without error, and that the data stored in volatile RAM
   was cryptographically compiled into permanent storage without tampering or alteration.

5. Technical Forensic Telephony Parameters Recorded at Incident:
   - Call Reference ID           : ${result.callId}
   - Call Duration               : ${result.durationSec} Seconds
   - Telephony Channel           : Mobile Cellular Telephony / VoLTE / VoIP
   - Deepfake Voice Probability  : ${(result.confidence * 100).toInt()}% (AASIST Spectro-Temporal Graph)
   - Extracted Threat Category   : ${result.scamType ?: "Suspected Voice Fraud"}
   - Extracted Financial IOCs    : Suspect UPI VPA: $upiStr
                                   Suspect Account: $acctStr

6. Verbatim Recorded Transcript Excerpt:
   "${result.fullTranscript.take(500)}"

7. That the accompanying printout / electronic document is an exact, un-tampered duplicate of the
   electronic forensic record generated by the device.

Date: $dateStr                                                Signature: _______________________
Place: [Current City]                                          Name: $complainantName
====================================================================================================
""".trimIndent()

        return StatutoryCertificate(
            certificateText = certificateText,
            sha256Checksum = sha256,
            timestampIso = isoTimestamp
        )
    }
}
